### PR TITLE
Adds a CRD `FrontendConfig` to redirect http --> https

### PR DESCRIPTION
**Pull request by PuneetPunamiya**
- This patch adds a CRD which is added as annotation
     in ui-ingress which helps to redirect from
     `http://hub.tekton.dev` to `https://hub.tekton.dev`

Signed-off-by: Puneet Punamiya <ppunamiy@redhat.com>

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/main/standards.md#principles) (if functionality changed/added)
- [ ] Run API Unit Tests, Lint Checks, API Design, Golden Files with `make api-check`
- [ ] Run UI Unit Tests, Lint Checks with `make ui-check`
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/main/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/main/CONTRIBUTING.md) for more details._

### CODE REVIEW

**Comment by PuneetPunamiya** [comment]
cc @afrittoli  Coud you please task a look at this once 🙂

**Review by afrittoli — COMMENTED** [review]
/lgtm

Thank you!

**Pull request merged**
