### PR TITLE
Removes Preview APIs for resources 🙃 

### PR DESCRIPTION
**Pull request by sm43**
When we announced v1 APIs for resources in Jan 2021, we also
said we are deprecating and would support the preview APIs
for atleast 9 months as per the API policy.
https://github.com/tektoncd/hub/blob/main/docs/API_POLICY.md
Now, that we have completed a year we can safe to remove preview
APIs.

-----
 Cleanup: removes unused types def

This removed unused types definition from types.go
also renames Tag to TagDef because of following error
```
goa gen github.com/tektoncd/hub/api/design
../design/types/type.go:23:5: Tag redeclared in this block
	/home/smukhade/go/src/github.com/tektoncd/hub/api/design/types/type.go:18:2: previous declaration during import "goa.design/goa/v3/dsl"
```
this is because there is a builtin `Tag` which is conflicting while
generation.

Signed-off-by: Shivam Mukhade <smukhade@redhat.com>

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/main/standards.md#principles) (if functionality changed/added)
- [ ] Run API Unit Tests, Lint Checks, API Design, Golden Files with `make api-check`
- [ ] Run UI Unit Tests, Lint Checks with `make ui-check`
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/main/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/main/CONTRIBUTING.md) for more details._

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]

**Review by PuneetPunamiya — COMMENTED** [review]
Not a blocker but could you please club second and third commit as ideally test should pass on individual commit, else the pr looks fine to me

**Comment by PuneetPunamiya** [comment]
Also please rebase your pr once

**Review by vinamra28 — COMMENTED** [review]
/lgtm

**Pull request merged**
