### PR TITLE
Replace maze.io/x/duration to git.maze.io/go/duration

### PR DESCRIPTION
**Pull request by piyush-garg**
This will replace maze.io/x/duration to git.maze.io/go/duration
as it is failing sometimes because of redirection

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/main/standards.md#principles) (if functionality changed/added)
- [ ] Run API Unit Tests, Lint Checks, API Design, Golden Files with `make api-check`
- [ ] Run UI Unit Tests, Lint Checks with `make ui-check`
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/main/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/main/CONTRIBUTING.md) for more details._

### CODE REVIEW

**Comment by piyush-garg** [comment]
Reason to do this https://github.com/tektoncd/cli/pull/1384

**Comment by PuneetPunamiya** [comment]
Thanks 🤙🏻 
/lgtm

**Review by vdemeester — APPROVED** [review]

**Pull request merged**
