### PR TITLE
feat: add new Virtual Machines category

### PR DESCRIPTION
**Pull request by ksimon1**
# Changes
This PR adds new category Virtual Machines for new tasks from KubeVirt tekton tasks project https://github.com/kubevirt/kubevirt-tekton-tasks.
/cc @vdemeester 

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/main/standards.md#principles) (if functionality changed/added)
- [ ] Run API Unit Tests, Lint Checks, API Design, Golden Files with `make api-check`
- [ ] Run UI Unit Tests, Lint Checks with `make ui-check`
- [ ] Commit messages follow [commit message best practices]

# Release Notes
```release-note
Add category Virtual Machines
```

### CODE REVIEW

**Comment by ksimon1** [comment]
@pratap0007 the failing test is probably not related to this PR. SHould I add the newly generated files to this PR?

**Comment by pratap0007** [comment]
> @pratap0007 the failing test is probably not related to this PR. SHould I add the newly generated files to this PR?

No, we have pr for newly generated files and once the pr get merged, will do retest for failing test

**Comment by piyush-garg** [comment]
Hey

Are you planning to add these tasks from https://github.com/kubevirt/kubevirt-tekton-tasks to tektoncd/catalog?

**Comment by ksimon1** [comment]
Yes, I just need to finish few stuff and then I would like to add them to tektoncd/catalog

**Comment by piyush-garg** [comment]
> Yes, I just need to finish few stuff and then I would like to add them to tektoncd/catalog

It will be better to merge this PR after that, otherwise it will just show the category with no resources

**Comment by ksimon1** [comment]
ok, so lets wait with this PR
/hold

**Pull request closed without merging**
