### PR TITLE
Remove username formatting(convert lowercase) while saving

### PR DESCRIPTION
**Pull request by kk-r**
Resolves: #288

# Changes
- Update user exists check logic for both lowercase & mixed-case username
    - Using `LOWER(github_login)` to prevent if user changed his username from mixed-case to lowercase in GitHub.
- Store updated username if the username in database is incorrect.
- Update existing testcase to support when new username contains mixed-case letters.

    - 
# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/main/standards.md#principles) (if functionality changed/added)
- [ ] Run API Unit Tests, Lint Checks, API Design, Golden Files with `make api-check`
- [x] Run UI Unit Tests, Lint Checks with `make ui-check`
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/main/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/main/CONTRIBUTING.md) for more details._

### CODE REVIEW

**Comment by kk-r** [comment]
Waiting

**Review by vinamra28 — COMMENTED** [review]
Hi @kk-r, thank you for your contribution 🤗
The PR overall looks good. Can you please add one more test case when GitHub username is in lowercase?
/ok-to-test

**Comment by kk-r** [comment]
@vinamra28 I have added new test case to handle username in mixed case. Also added logic to verify not to create a new user when GH returns username in mixed case. I hope all possible test scenarios are covered, let me know if anything missing. 

Thanks!

**Comment by kk-r** [comment]
Seems there is issue on EasyCLA integration. So I'll close this PR and create new one.
image

**Pull request closed without merging**
