### PR TITLE
Disables search in the sort by dropdown

### PR DESCRIPTION
**Pull request by pratap0007**
- This patch disables search in the sort by dropdown as sort-by have only 3 items, so disabled search, in case of long list of sort-by options would be good to have search

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/main/standards.md#principles) (if functionality changed/added)
- [ ] Run API Unit Tests, Lint Checks, API Design, Golden Files with `make api-check`
- [x] Run UI Unit Tests, Lint Checks with `make ui-check`
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/main/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/main/CONTRIBUTING.md) for more details._

### CODE REVIEW

**Comment by PuneetPunamiya** [comment]
Thanks 🤙🏻 
/approve

**Comment by vinamra28** [comment]
@pratap0007 could you please state why are we disabling the search in dropdown(although that's not a required feature but just for logging purpose)?

**Comment by pratap0007** [comment]
> @pratap0007 could you please state why are we disabling the search in dropdown(although that's not a required feature but just for logging purpose)?

as soryby have only 3 items, so disabled search, in case of long list of sortby options would be good to have search

**Comment by vinamra28** [comment]
> > @pratap0007 could you please state why are we disabling the search in dropdown(although that's not a required feature but just for logging purpose)?
> 
> as soryby have only 3 items, so disabled search, in case of long list of sortby options would be good to have search

thanks.
/lgtm

**Pull request merged**
