### PR TITLE
Allow installing Hub tasks on development version of Pipelines

### PR DESCRIPTION
**Pull request by lbernick**
# Changes

The Pipelines version is pulled from the labels of the Tekton Pipelines controller, which is "devel" for the development version. 
Error example: `tkn hub install task golang-build` returns "Error: Task golang-build(0.2) requires Tekton Pipelines min version v0.12.1 but found devel".
This change should allow pipelines developers to install Hub tasks on their installation of pipelines.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/main/standards.md#principles) (if functionality changed/added)
- [ ] Run API Unit Tests, Lint Checks, API Design, Golden Files with `make api-check`
- [ X ] Run UI Unit Tests, Lint Checks with `make ui-check`
- [ X ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/main/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/main/CONTRIBUTING.md) for more details._

### CODE REVIEW

**Review by vinamra28 — COMMENTED** [review]
/lgtm

**Comment by sm43** [comment]
would it be nice if we print a warning ? 🤔 
because in case of `devel` the task may or may not be compatible?

**Comment by lbernick** [comment]
Happy to add a warning if desired, although I think `devel` users expect occasional compatibility issues (?)
Could you help me figure out why the tests are failing here? It looks like the tests are not able to connect to postgres, but I'm not sure how to fix.

**Comment by sm43** [comment]
> Happy to add a warning if desired, although I think `devel` users expect occasional compatibility issues (?)

yeah I agree ! lets move ahead without warning,
> Could you help me figure out why the tests are failing here? It looks like the tests are not able to connect to postgres, but I'm not sure how to fix.

it seems to be an network issue. was failing to download postgres.

Thanks for the PR :)
/approve

**Pull request merged**
