### PR TITLE
Fix Swagger UI Catalog example error

### PR DESCRIPTION
**Pull request by QuanZhang-William**
Prior to this commit, "tektoncd" is used as catalog example in the "resouce" section of Swagger UI, which results in 404 issue when trying out the example. This commit fixes the issue by correcting "tektoncd" to "tekton"

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/main/standards.md#principles) (if functionality changed/added)
- [ ] Run API Unit Tests, Lint Checks, API Design, Golden Files with `make api-check`
- [ ] Run UI Unit Tests, Lint Checks with `make ui-check`
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/main/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/main/CONTRIBUTING.md) for more details._

### CODE REVIEW

**Review by vinamra28 — APPROVED** [review]
/meow
/cc @piyush-garg @PuneetPunamiya

**Comment by PuneetPunamiya** [comment]
Thanks for the pr, the patch looks fine but I have a small concern about this because we are adding these examples in goa design to showcase user what all values can be added, but for the beginners it might be confusing as well

/lgtm

**Comment by QuanZhang-William** [comment]
@PuneetPunamiya I have updated the PR description and added some screenshots to show the issue better. Hope this is clearer to beginners like me 😄

**Pull request merged**
